version: 0.1
component: build
timeoutInSeconds: 600
runAs: root
shell: bash
env:
  variables:
#     "version" : "3.4"
    "repoName": "docktest"
    "major_version": "4"
    "minor_version": "4"
    
  exportedVariables:
    - minor_version
#     - version
    - major_version
    - repoName

steps:
  - type: Command
    name: "PreReq install"
    command: |
      yum -y install curl
  - type: Command
    name: "Dockerize"
    command: |
      docker build -t docktest .
  - type: Command
    name: "Save"
    command: |
      docker save docktest -o docktest.tar
  - type: Command
    name: "SaveResult"
    command: |
      ls >> dockImagesResult.txt
#   - type: Command
#     name: "SaveResult"
#     command: |
#       export major_version=1.2

outputArtifacts:
  - name: docktest    # Eg: foo-java-app
    type: BINARY     # Enum: [BINARY, DOCKER_IMAGE]
    location: docktest.tar 
  - name: docktestImage    # Eg: foo-java-app
    type: DOCKER_IMAGE     # Enum: [BINARY, DOCKER_IMAGE]
    location: docktest
